package compose

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/necrogami/devtools/internal/hostenv"
)

// OverrideFile returns the absolute path to a project's
// docker-compose.override.yml. Compose auto-loads this file when it sits
// alongside docker-compose.yml, so no -f flag is needed at the call site.
func OverrideFile(projectDir string) string {
	return filepath.Join(projectDir, "docker-compose.override.yml")
}

// In-container destination paths — kept in one place so the override
// renderer and any future docs stay in lock-step.
const (
	containerSSHSock        = "/run/host/ssh-agent"
	containerGPGSock        = "/run/host/gpg-agent"
	containerKeyboxdSock    = "/run/host/keyboxd"
	containerGPGHome        = "/home/dev/.gnupg"
	containerHomeGitCfg     = "/home/dev/.gitconfig"
	containerGHConfigDir    = "/home/dev/.config/gh"
	containerClaudeSettings = "/home/dev/.claude/settings.json"
	containerClaudeMd       = "/home/dev/.claude/CLAUDE.md"
	containerClaudeAgents   = "/home/dev/.claude/agents"
)

// overrideHeader is the "you didn't write this" notice prepended to every
// rendered override. It also tells users where the file comes from and that
// editing it is pointless (dev up overwrites).
const overrideHeader = `# GENERATED by 'dev up' from host discovery — do not edit.
#
# This override layers host-specific credential/agent bind-mounts onto
# docker-compose.yml. The set of mounts depends on what ` + "`" + `internal/hostenv` + "`" + `
# finds on the current host at run time, so the file differs between
# machines (and should not be committed). ` + "`" + `dev up` + "`" + ` rewrites it on
# every invocation; delete it any time — it will come back.
`

// RenderOverride writes a docker-compose.override.yml representing the
// credential/agent bind-mounts derived from creds. Fields that are empty
// in creds are simply omitted, producing graceful degradation on hosts
// without the corresponding tooling (no gpg, no ssh-agent, etc.).
func RenderOverride(creds hostenv.HostCreds, w io.Writer) error {
	var b strings.Builder
	b.WriteString(overrideHeader)
	b.WriteString("\n")
	b.WriteString("services:\n")
	b.WriteString("  tools:\n")

	// environment: only SSH_AUTH_SOCK, and only when we actually mount a
	// socket. If we don't, leaving the var unset inside the container lets
	// ssh fall back sanely (prompt / fail loudly rather than try to connect
	// to a bogus socket).
	if creds.SSHAgentSock != "" {
		b.WriteString("    environment:\n")
		b.WriteString(fmt.Sprintf("      SSH_AUTH_SOCK: %s\n", containerSSHSock))
	}

	mounts := buildMounts(creds)
	if len(mounts) == 0 {
		// Still emit a valid (if minimal) services block so compose
		// doesn't complain about a malformed override.
		b.WriteString("    # no host credentials discovered; nothing to forward\n")
		_, err := io.WriteString(w, b.String())
		return err
	}

	b.WriteString("    volumes:\n")
	for _, m := range mounts {
		b.WriteString(fmt.Sprintf("      - %s\n", m))
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// WriteOverride renders and persists docker-compose.override.yml into the
// given project directory. Overwrites any existing file (the override is
// entirely a function of host state + the renderer, and is .gitignored).
func WriteOverride(projectDir string, creds hostenv.HostCreds) error {
	path := OverrideFile(projectDir)
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create override: %w", err)
	}
	defer f.Close()
	if err := RenderOverride(creds, f); err != nil {
		return fmt.Errorf("render override: %w", err)
	}
	return nil
}

// buildMounts returns the ordered slice of compose short-form volume specs
// for the non-empty fields in creds. Order is stable across calls (agents
// first, then gpg, then git/gh, then claude) so the rendered file diffs
// meaningfully when the host state changes.
func buildMounts(c hostenv.HostCreds) []string {
	var m []string

	if c.SSHAgentSock != "" {
		m = append(m, c.SSHAgentSock+":"+containerSSHSock)
	}
	if c.GPGAgentSock != "" {
		m = append(m, c.GPGAgentSock+":"+containerGPGSock)
	}
	if c.KeyboxdSock != "" {
		m = append(m, c.KeyboxdSock+":"+containerKeyboxdSock)
	}

	if c.GPGCommonConf != "" {
		m = append(m, c.GPGCommonConf+":"+containerGPGHome+"/common.conf:ro")
	}
	if c.GPGKeyboxDir != "" {
		m = append(m, c.GPGKeyboxDir+":"+containerGPGHome+"/public-keys.d:ro")
	}
	if c.GPGPubringKbx != "" {
		m = append(m, c.GPGPubringKbx+":"+containerGPGHome+"/pubring.kbx:ro")
	}
	if c.GPGTrustdb != "" {
		m = append(m, c.GPGTrustdb+":"+containerGPGHome+"/trustdb.gpg:ro")
	}
	if c.GPGOwnerTrust != "" {
		m = append(m, c.GPGOwnerTrust+":"+containerGPGHome+"/ownertrust:ro")
	}

	if c.GitConfig != "" {
		m = append(m, c.GitConfig+":"+containerHomeGitCfg+":ro")
	}
	if c.GHConfig != "" {
		m = append(m, c.GHConfig+":"+containerGHConfigDir+":ro")
	}

	if c.ClaudeSettings != "" {
		m = append(m, c.ClaudeSettings+":"+containerClaudeSettings+":ro")
	}
	if c.ClaudeMd != "" {
		m = append(m, c.ClaudeMd+":"+containerClaudeMd+":ro")
	}
	if c.ClaudeAgents != "" {
		m = append(m, c.ClaudeAgents+":"+containerClaudeAgents+":ro")
	}

	return m
}
